name: iOS Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0' 

    - name: Set Environment Variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
        echo "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> $GITHUB_ENV
        echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> $GITHUB_ENV
        echo "SMS_SERVICE_URL=${{ secrets.SMS_SERVICE_URL }}" >> $GITHUB_ENV
        echo "SMS_SERVICE_EMAIL=${{ secrets.SMS_SERVICE_EMAIL }}" >> $GITHUB_ENV
        echo "SMS_SERVICE_API_KEY=${{ secrets.SMS_SERVICE_API_KEY }}" >> $GITHUB_ENV


    - name: Build the App
      run: xcodebuild -workspace MakeSure.xcworkspace -scheme MakeSure -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=NO


    # Add any additional steps, like testing, if necessary
